name: premerge

on:
  pull_request:
    types: [
        # Default pull_request trigger types.
        opened,
        synchronize,
        reopened,
      ]
  push:
    branches: [main]

jobs:
  lint_and_fast_tests:
    runs-on: ubuntu-latest
    steps:
      # Basic setup
      - uses: actions/checkout@v2
        with:
          clean: 'false'
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 15.14.0
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Setup git
        run: git config --global user.email "test@gmail.com" && git config --global user.name "test"
      - name: Git Version
        run: git --version
      - name: Test
        run: yarn test-ci
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

  superlinter:
    # Name the Job
    name: Run Superlinter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
